# Generated by Django 2.2.1 on 2019-06-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salary', models.IntegerField()),
                ('Comment', models.TextField()),
                ('Expense_categories', models.CharField(max_length=120)),
                ('Credit_Transactions', models.IntegerField()),
                ('Debit_Transactions', models.IntegerField()),
                ('Expenses', models.IntegerField()),
            ],
        ),
    ]
