# Generated by Django 2.2.1 on 2019-06-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Day',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
    ]
